version: '3.9'

services:
  proxy:
    depends_on:
      - parser_shop_api
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - "443:443"

  parser_shop_api:
    env_file:
      - ../.env/.env
    depends_on:
      - redis
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    volumes:
      - ../logs:/app/logs
      - ../files:/app/files

  redis:
    image: redis:7.2.3
    restart: on-failure
